name: Build `macup`

on:
  push:
    branches:
      - ${{ github.default_branch }}
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Install dependencies (Go)
        run: go mod download
        if: exists('go.mod')
      - name: Build Go project
        run: make all
        if: exists('go.mod')
      - name: Run Go tests
        run: make test
        if: exists('go.mod')
