name: Release MacUp

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: macos-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build Go project
        run: make all
      # TODO: Will do in near future, need to rethink the release process
      # - name: Create Release
      #   if: success()
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     name: Release ${{ github.ref_name }}
      #     body: "Automated release for commit ${{ github.sha }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
