name: Test
on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - master
jobs:
  test:
    name: Test Update Script
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Test
        run: |
          zsh update-all.sh || { echo "The script exited with an error."; exit 1; }
          echo "The script executed successfully."
