name: Test
on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - master
jobs:
  test:
    name: Test Update Script
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Test
        run: |
          set -x # Enable Execution Logs
          zsh install.sh || { echo "The script exited with an error."; exit 1; }
          echo "The script executed successfully."
          ZSHRC_PATH="${HOME}/.zshrc"
          source ${ZSHRC_PATH}
          UPDATE_ALIAS_SEARCH_STR="curl -fsSL https://raw.githubusercontent.com/andmpel/MacOS-All-In-One-Update-Script/HEAD/update-all.sh | ${SHELL}"
          if ! grep -qxF "${UPDATE_ALIAS_SEARCH_STR}" "${ZSHRC_PATH}"; then
            echo "Error: Test Failed!!!"
            exit 1
          fi
          echo "TEST PASSED"
